### ISSUE TITLE
Can't clone repository, Aux.odc is illegal file name in Windows

### ISSUE THREAD

**Issue by X547** [adimetrius/Herschel#2]
Problem file: https://github.com/adimetrius/Herschel/blob/master/Hr/Mod/Aux.odc

Related information: https://stackoverflow.com/questions/48960479/unable-to-index-file

Windows do not allow to create files with old DOS device names (CON, AUX, NUL, PRN, etc.) even if file has extension.

**Comment by iadenisov** [comment]
fixed
